### PR TITLE
use sysroot_linux-64=2.17 on linux

### PR DESCRIPTION
**Pull request by esc**
As per https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7

### CODE REVIEW

**Comment by esc** [comment]
Looks good! Awkward passed.

**Comment by seibert** [comment]
just to make sure I understand:  The reason this extra constraint needs to be added is because `conda-forge` is in the channel list, and they have later glibc options?

**Comment by esc** [comment]
@seibert indeed, the other fix might be to stop using conda-forge, because the compilers have caught up by now?

**Comment by seibert** [comment]
I think this is fine for now, but at least we have noted the need for the workaround.

**Pull request merged**
