### PR TITLE
remove the Numba dependency for clifford

### PR DESCRIPTION
**Pull request by esc**
As title.

### CODE REVIEW

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by stuartarchibald** [comment]
Presume `clifford` is failing CI for different reasons?

**Comment by esc** [comment]
> Presume `clifford` is failing CI for different reasons?

indeed.

**Comment by stuartarchibald** [comment]
@esc feel free to merge this as convenient.

**Pull request merged**
