### PR TITLE
Update awkward

### PR DESCRIPTION
**Pull request by esc**

### CODE REVIEW

**Comment by jpivarski** [comment]
```
Traceback (most recent call last):
  File "switchboard.py", line 248, in <module>
    main(NumbaSource())
  File "/usr/local/lib/python3.6/site-packages/texasbbq.py", line 389, in main
    run(source, args.stages, available_targets, args.targets)
  File "/usr/local/lib/python3.6/site-packages/texasbbq.py", line 367, in run
    target.install()
  File "/usr/local/lib/python3.6/site-packages/texasbbq.py", line 276, in install
    os.chdir(self.name)
FileNotFoundError: [Errno 2] No such file or directory: 'awkward'
Exited with code 1
```

The new repo name is "`awkward1`" (with a `1`) because there will be a deprecation phase for the users early next year.

But it looks like you just got it and updated it.

**Comment by esc** [comment]
https://circleci.com/gh/numba/numba-integration-testing/1228

**Comment by esc** [comment]
Getting closer.

**Comment by jpivarski** [comment]
Great! I can see that it ran the Numba tests and was successful. This is the testing procedure I'd like to switch to.

Will it be triggered by each merge into `awkward1:master`? I can keep an eye on it as I merge in PRs. (Of course I'm watching my own tests, but they're based on released versions of Numba; presumably, this would give me advance warning on upcoming changes in Numba.)

Thanks!

**Comment by esc** [comment]
They will run for every merge to `numba/master` using whatsver is specified in the `clone` command. Most the other projects have logic to determine what the latest release is from the available tags and then use that as basis.

**Comment by esc** [comment]
Usually, we try to test the `numba/master` against released versions of libraries, to make sure we don't break our downstream dependents during development.

**Comment by jpivarski** [comment]
I see—then it will be testing master of both awkward1 and numba. I'll be sure to keep awkward1's master clean. Thanks!

**Comment by esc** [comment]
clifford and pygbm are known to be failing right now, not sure about sparse...

**Comment by esc** [comment]
O.K. sparse is failing on master too.

**Comment by esc** [comment]
pyspare tests maybe fixed here: https://github.com/numba/numba-integration-testing/pull/24

**Comment by esc** [comment]
@jpivarski regarding which version of `awkward1` will be used: there is some logic in TeaxsBBQ which will scan the tags and try to fetch the most recent one. So which version of `awkward1` will be used depends on what kind of tags you have pushed to that repo.

BTW: numba/texasbbq#6 has been merged now, so this would be good to go too, I believe.

**Comment by jpivarski** [comment]
Okay, then I'll make sure the latest tag is clean. (It's a released version, so of course.)

Thanks!

**Comment by esc** [comment]
@jpivarski indeed, but no worries, I will keep an eye on the builds and let you know if we break anything.

**Comment by esc** [comment]
I updated the URl for Awkward-1.0

**Comment by jpivarski** [comment]
A week ago, we did a major overhaul of Awkward's build system, and I found out things like, "one must never install via `python setup.py install` anymore."

Our formal testing procedure is now:

https://github.com/scikit-hep/awkward-1.0/blob/e60faf1bf1815b44124a71f444c969194118481d/.ci/azure-buildtest-awkward.yml#L197-L202

but this involves _installing_ Awkward into lib/pythonX.Y/site-packages, lib (for the .so files), and include (for the .h files). You might not want that. You could limit this step's impact by running it in a virtual environment,

```bash
python -m venv .env
source .env/bin/activate
python -m pip install -v .[test,dev]
python -m pytest -vv -rs tests
deactivate
```

or you could use the development script that we have for local testing,

```bash
python localbuild.py --pytest tests
```

The localbuild.py (incrementally) compiles and tests everything in a local directory and does not install it.

Which do you think would be best for your CircleCI environment?

**Comment by esc** [comment]
@jpivarski thanks for getting back to me about this, the CircleCI thing is quite flexible, using `python localbuild.py --pytest tests` seems to be what I want, I'll patch it now and see what circle CI says.

**Comment by esc** [comment]
@jpivarski also, I was wondering if this is the correct clone command:

```
git clone https://github.com/scikit-hep/awkward-1.0.git --recursive awkward
```

?

**Comment by jpivarski** [comment]
Yes, you still need to do a recursive clone.

The name conflict you saw last time (the last I remembered) is gone: the two files in the same directory with different capitalizations have been removed (for other reasons).

**Comment by esc** [comment]
@jpivarski yes, it is looking good, we are now at the (expected) import error from Numba, so now we wait for #34 to complete.

**Comment by esc** [comment]
@stuartarchibald I believe this can now be reviewed by you.

**Comment by stuartarchibald** [comment]
On the basis that CI is going to fail as everything got moved, the code change seems reasonable given what I might expect a build to comprise. Thanks for the patch, let's hope #34 works :)

**Review by stuartarchibald — APPROVED** [review]

**Comment by esc** [comment]
@stuartarchibald thank you!

**Pull request merged**
