### PR TITLE
Fix awkward-array tag detection

### PR DESCRIPTION
**Pull request by esc**
Rename the awkward-array project to awkward internally again and fix it's tag detection.

### CODE REVIEW

**Comment by esc** [comment]
@jpivarski any chance you could review this? I did fixup custom clones in #4 -- so the naming should all work now.

**Comment by jpivarski** [comment]
I don't get an official "review" button, but I can review it in a comment. It looks good to me, though (now that I see the log output) I wish I'd said "`pytest -v`" instead of just "`pytest`". It's only one test file, so seeing all the individual test functions on separate lines would be nice. That's not a big deal, though.

Pinning awkward to `numba==0.43.1` fixes that interface-change issue, but that's a temporary fix. Either I need to start using `iternext_impl` in a version-independent way (check Numba version and use it as a function-call, rather than a decorator, which deteriorates readability) or `iternext_impl` needs to become backward-compatible. No released versions of Numba have the new interface yet, so there's still time to do that.

As I understand it, discovering these issues at the surface between Numba and its dependencies is the reason you're doing these tests. What's the procedure for asking my question? Who do I ask about possibly making `iternext_impl` backward compatible? (The answer can be "no"—I just want to ask the right person. It will probably happen again, so it would be good to have a procedure. Thanks!)

**Comment by esc** [comment]
@jpivarski thanks for the review, I have added `-v`.

**Comment by esc** [comment]
Awkward is passing, because this doesn't include #6

**Comment by stuartarchibald** [comment]
@jpivarski Please could you post API change queries on the [Numba issue tracker](https://github.com/numba/numba/issues), I think a couple of projects have been hit by using an internal API that has changed and it'd be good to make these issues visible and on the radar for core developers. Many thanks for your help.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. Looks good and @jpivarski (code owner of integrated project) has approved. Merging.

**Pull request merged**
