### PR TITLE
new command to run tests for pysparse

### PR DESCRIPTION
**Pull request by esc**

### CODE REVIEW

**Comment by esc** [comment]
This fixes the pysparse tests, ready for review and merge.

**Comment by esc** [comment]
will re-roll this one

**Comment by esc** [comment]
@eric-wieser do you happen to know if this PR is good?

**Comment by esc** [comment]
This line does seem to indicate so:

https://github.com/pydata/sparse/blob/master/ci/azure-steps.yml#L13

**Comment by eric-wieser** [comment]
@hameerabbasi is the person to ask here

**Comment by hameerabbasi** [comment]
You need `pip install -e .[tests]` in addition.

**Comment by hameerabbasi** [comment]
Ah, I see that you already have `pip install -e .[all]`. This should be good.

**Comment by esc** [comment]
@eric-wieser @hameerabbasi thanks for your feedback!

**Comment by stuartarchibald** [comment]
Thanks for the fixes/checking etc. Looks good.

**Comment by esc** [comment]
@stuartarchibald thanks for merging!

**Pull request merged**
