### PR TITLE
adding pygbm

### LINKED ISSUE #11: Add pygbm to the test matrix
https://github.com/ogrisel/pygbm

### PR DESCRIPTION
**Pull request by esc**
Fixes #11

### CODE REVIEW

**Comment by esc** [comment]
Over half of the tests are failing on `v0.1.0`, here is the CI log:

https://circleci.com/gh/numba/numba-integration-testing/542

**Comment by ogrisel** [comment]
I cannot reproduce the failure locally with numba 0.44.1. Here is the conda env I used:

```
atomicwrites              1.2.1                    py37_0  
attrs                     18.2.0           py37h28b3542_0  
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2019.6.16                py37_0  
expat                     2.2.6                he6710b0_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
fribidi                   1.0.5                h7b6447c_0  
glib                      2.56.2               hd408876_0  
graphite2                 1.3.12               h23475e2_2  
graphviz                  2.40.1               h21bd128_2  
harfbuzz                  1.8.8                hffaf4a1_0  
icu                       58.2                 h9c2bf20_1  
importlib-metadata        0.18                      <pip>
intel-openmp              2019.1                      144  
joblib                    0.13.0                   py37_0  
jpeg                      9b                   h024ee3a_2  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.35               hbc83047_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.9                he85c1e1_2  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
lightgbm                  2.2.2                     <pip>
llvmlite                  0.29.0           py37hd408876_0  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py37h7dd41cf_0  
mkl_random                1.0.1            py37h4414c95_1  
more-itertools            4.3.0                    py37_0  
ncurses                   6.1                  he6710b0_1  
numba                     0.44.1           py37h962f231_0  
numpy                     1.15.4           py37h1d66e8a_0  
numpy-base                1.15.4           py37h81de0dd_0  
openssl                   1.1.1c               h7b6447c_1  
packaging                 19.0                      <pip>
pandas                    0.23.4           py37h04863e7_0  
pango                     1.42.4               h049681c_0  
pcre                      8.42                 h439df22_0  
pip                       18.1                     py37_0  
pixman                    0.34.0               hceecf20_3  
pluggy                    0.12.0                    <pip>
pluggy                    0.8.0                    py37_0  
py                        1.7.0                    py37_0  
pygbm                     0.1.0                     <pip>
pyparsing                 2.4.0                     <pip>
pytest                    4.0.1                    py37_0  
pytest                    5.0.0                     <pip>
python                    3.7.1                h0371630_3  
python-dateutil           2.7.5                    py37_0  
pytz                      2018.7                   py37_0  
readline                  7.0                  h7b6447c_5  
scikit-learn              0.20.1           py37h4989274_0  
scipy                     1.1.0            py37hfa4b5c9_1  
setuptools                40.6.2                   py37_0  
six                       1.11.0                   py37_1  
sqlite                    3.25.3               h7b6447c_0  
tbb                       2019.1               hfd86e86_0  
tk                        8.6.8                hbc83047_0  
wcwidth                   0.1.7                     <pip>
wheel                     0.32.3                   py37_0  
xz                        5.2.4                h14c3975_4  
zipp                      0.5.1                     <pip>
zlib                      1.2.11               h7b6447c_3 
```

**Comment by ogrisel** [comment]
It seems to be a regression of `_analyze_op_call_numpy_reshape`. Maybe you could launch pytest with `pytest -vl` to get a more verbose output and in particular display the value of local variables in tracebacks.

**Comment by esc** [comment]
Oh wow, I can confirm that this works fine with the `0.44.1` release, so it would appear that the integration test might be pointing to a possible regression. cc @seibert

**Comment by esc** [comment]
[out.txt](https://github.com/numba/numba-integration-testing/files/3346337/out.txt)

The log of `pytest -vl`  is attached.

**Comment by seibert** [comment]
This does look like a regression.  @val: Can you open a new issue over on the Numba tracker with instructions on how to run just the failing test so someone can triage it?

**Comment by esc** [comment]
@seibert looks like all is well with the new dev-builds from the numba channel. Can you give it a quick review and merge if good?

**Comment by seibert** [comment]
Looks good.  Glad to see pygbm added to the test suite!

**Comment by esc** [comment]
Indeed, it also means we probably won't break pygbm with the next release 🤞

**Comment by ogrisel** [comment]
Thanks!

**Comment by esc** [comment]
So it ran this morning again, ran into a timeout error, but succeeded when run again. I will be keeping an eye on it.

**Pull request merged**
