### PR TITLE
Fix clifford

### PR DESCRIPTION
**Pull request by esc**

### CODE REVIEW

**Comment by esc** [comment]
Yay, clifford is green.

**Comment by esc** [comment]
This is ready for review when the Clifford tests go green.

**Comment by eric-wieser** [comment]
Is the <3.9 requirement a clifford thing, or just something you're doing to all your tests?

**Comment by esc** [comment]
@eric-wieserit since Numba does not support 3.9 it is something I tend to add in case the dependencies of the target (the project to be tested against) and it's dependencies don't already include that limitation.

**Comment by esc** [comment]
Oh snap! It looks like the Clifford tests failed due to a numerical instability in one of the tests:

```
=================================== FAILURES ===================================
_________________ TestG3CTools.test_get_midpoint_between_lines _________________

self = <clifford.test.test_g3c_tools.TestG3CTools object at 0x7f277302e700>

    def test_get_midpoint_between_lines(self):
        for i in range(50):
            P = random_conformal_point()
            T1 = random_translation_rotor()
            T2 = random_translation_rotor()
            P1 = apply_rotor(P, T1)
            P2 = apply_rotor(P, T2)
            L1 = (P ^ P1 ^ einf).normal()
            L2 = (P ^ P2 ^ einf).normal()
            Pmid = midpoint_between_lines(L1, L2)
            assert_allclose(Pmid.value, P.value)
        for i in range(50):
            L1 = random_line()
            L2 = random_line()
            Pmid = midpoint_between_lines(L1, L2)
            L1point = project_points_to_line([Pmid], L1)[0]
            L2point = project_points_to_line([Pmid], L2)[0]
            dst = euc_dist(L1point, L2point)
            middst1 = euc_dist(Pmid, L1point)
            middst2 = euc_dist(Pmid, L2point)
>           npt.assert_allclose(dst, 2 * middst1)
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=0
E           
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 9.34113041e-08
E           Max relative difference: 1.17114052e-06
E            x: array(0.079761)
E            y: array(0.079761)

clifford/test/test_g3c_tools.py:496: AssertionError
```

I'll re-run it now.

**Comment by eric-wieser** [comment]
Apologies for that - our tests are notoriously numerically unstable, as @hugohadfield got a little too excited about using randomized testing to eek out bugs at the expense of determinism.

**Comment by esc** [comment]
Yeah, I am aware and have already reported a few of these to @hugohadfield -- luckily they are easy enough to spot!

**Comment by hugohadfield** [comment]
Sorry about that everyone!

**Comment by esc** [comment]
Alright, it is fine now! 🎉

**Review by stuartarchibald — APPROVED** [review]

**Comment by stuartarchibald** [comment]
Thanks for fixing this.

**Pull request merged**
