### PR TITLE
add integration tests for awkward-array

### PR DESCRIPTION
**Pull request by jpivarski**
I followed the instructions for adding the awkward-array test, though I don't understand the testing framework well enough to run it myself. However, I think the form I filled out should make my intent clear.

Thanks!

### CODE REVIEW

**Comment by esc** [comment]
@jpivarski awesome! This looks good, I'll try it now.

**Comment by esc** [comment]
This pretty much worked. I had to make the following two changes. The name of the project must be the name of the repository for now. While this is not set in stone, this is a requirement right now. Also Doing an `execute("cd bla")` won't succeed but instead I had to use `os.chdir`.  

Additionally, there was a test failure which I will be able to link to soon, once the tests have run through on CircleCI.

Did you find the documentation useful? Does it still lack something?

**Comment by esc** [comment]
For reference, here is the commit: https://github.com/numba/numba-integration-testing/commit/688e89b19f2f90e6b2d9791bcad03c3edc0cf9d8

**Comment by esc** [comment]
It looks good on linux on CI: https://circleci.com/gh/numba/numba-integration-testing/58

**Comment by esc** [comment]
Locally, I have a failure on MacOSX:

```
============================================================================== FAILURES ===============================================================================
_______________________________________________________________________ Test.test_numba_getiter _______________________________________________________________________

fmt_ = 'lowering "{inst}" at {loc}', args = ()
kwargs = {'inst': <numba.ir.Assign object at 0x11cf5b5f8>, 'loc': Loc(filename=/Users/vhaenel/git/numba-integration-testing/awkward/tests/test_numba.py, line=369, col=None)}
errcls = functools.partial(<class 'numba.errors.LoweringError'>, loc=Loc(filename=/Users/vhaenel/git/numba-integration-testing/awkward/tests/test_numba.py, line=369, col=None))
loc = Loc(filename=/Users/vhaenel/git/numba-integration-testing/awkward/tests/test_numba.py, line=369, col=None)
newerr = LoweringError('Failed in nopython mode pipeline (step: nopython mode backend)\nouter() takes 1 positional argument but...ore developers\ndirectly at: https://gitter.im/numba/numba\n\nThanks in advance for your help in improving Numba!\n\n')
config = <module 'numba.config' from '/Users/vhaenel/git/numba-integration-testing/miniconda3/envs/awkward/lib/python3.7/site-packages/numba/config.py'>, tb = None

    @contextlib.contextmanager
    def new_error_context(fmt_, *args, **kwargs):
        """
        A contextmanager that prepend contextual information to any exception
        raised within.  If the exception type is not an instance of NumbaError,
        it will be wrapped into a InternalError.   The exception class can be
        changed by providing a "errcls_" keyword argument with the exception
        constructor.

        The first argument is a message that describes the context.  It can be a
        format string.  If there are additional arguments, it will be used as
        ``fmt_.format(*args, **kwargs)`` to produce the final message string.
        """
        errcls = kwargs.pop('errcls_', InternalError)

        loc = kwargs.get('loc', None)
        if loc is not None and not loc.filename.startswith(_numba_path):
            loc_info.update(kwargs)

        try:
>           yield

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/errors.py:627:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <numba.lowering.Lower object at 0x11ee85cf8>, block = <ir.Block at /Users/vhaenel/git/numba-integration-testing/awkward/tests/test_numba.py (369)>

    def lower_block(self, block):
        """
        Lower the given block.
        """
        self.pre_block(block)
        for inst in block.body:
            self.loc = inst.loc
            defaulterrcls = partial(LoweringError, loc=self.loc)
            with new_error_context('lowering "{inst}" at {loc}', inst=inst,
                                   loc=self.loc, errcls_=defaulterrcls):
>               self.lower_inst(inst)

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/lowering.py:258:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <numba.lowering.Lower object at 0x11ee85cf8>, inst = <numba.ir.Assign object at 0x11cf5b5f8>

    def lower_inst(self, inst):
        # Set debug location for all subsequent LL instructions
        self.debuginfo.mark_location(self.builder, self.loc)
        self.debug_print(str(inst))
        if isinstance(inst, ir.Assign):
            ty = self.typeof(inst.target.name)
>           val = self.lower_assign(ty, inst)

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/lowering.py:301:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <numba.lowering.Lower object at 0x11ee85cf8>, ty = pair<array(float64, 1d, C), bool>, inst = <numba.ir.Assign object at 0x11cf5b5f8>

    def lower_assign(self, ty, inst):
        value = inst.value
        # In nopython mode, closure vars are frozen like globals
        if isinstance(value, (ir.Const, ir.Global, ir.FreeVar)):
            res = self.context.get_constant_generic(self.builder, ty,
                                                    value.value)
            self.incref(ty, res)
            return res

        elif isinstance(value, ir.Expr):
>           return self.lower_expr(ty, value)

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/lowering.py:459:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <numba.lowering.Lower object at 0x11ee85cf8>, resty = pair<array(float64, 1d, C), bool>, expr = iternext(value=$phi10.1)

    def lower_expr(self, resty, expr):
        if expr.op == 'binop':
            return self.lower_binop(resty, expr, expr.fn)
        elif expr.op == 'inplace_binop':
            lty = self.typeof(expr.lhs.name)
            if lty.mutable:
                return self.lower_binop(resty, expr, expr.fn)
            else:
                # inplace operators on non-mutable types reuse the same
                # definition as the corresponding copying operators.)
                return self.lower_binop(resty, expr, expr.immutable_fn)
        elif expr.op == 'unary':
            val = self.loadvar(expr.value.name)
            typ = self.typeof(expr.value.name)
            # Get function
            signature = self.fndesc.calltypes[expr]
            impl = self.context.get_function(expr.fn, signature)
            # Convert argument to match
            val = self.context.cast(self.builder, val, typ, signature.args[0])
            res = impl(self.builder, [val])
            res = self.context.cast(self.builder, res,
                                    signature.return_type, resty)
            return res

        elif expr.op == 'call':
            res = self.lower_call(resty, expr)
            return res

        elif expr.op == 'pair_first':
            val = self.loadvar(expr.value.name)
            ty = self.typeof(expr.value.name)
            res = self.context.pair_first(self.builder, val, ty)
            self.incref(resty, res)
            return res

        elif expr.op == 'pair_second':
            val = self.loadvar(expr.value.name)
            ty = self.typeof(expr.value.name)
            res = self.context.pair_second(self.builder, val, ty)
            self.incref(resty, res)
            return res

        elif expr.op in ('getiter', 'iternext'):
            val = self.loadvar(expr.value.name)
            ty = self.typeof(expr.value.name)
            signature = self.fndesc.calltypes[expr]
            impl = self.context.get_function(expr.op, signature)
            [fty] = signature.args
            castval = self.context.cast(self.builder, val, ty, fty)
>           res = impl(self.builder, (castval,))

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/lowering.py:942:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <wrapped <function _wrap_missing_loc.<locals>.wrapper at 0x11e5d1bf8>>, builder = <llvmlite.llvmpy.core.Builder object at 0x11deb50f0>
args = (<ir.LoadInstr '.154' of type '{i64*, {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, i64*, [1..., [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}, i1}}*', opname 'alloca', operands ()>]>,)
loc = None

    def __call__(self, builder, args, loc=None):
>       res = self._imp(self._context, builder, self._sig, args, loc=loc)

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/targets/base.py:1132:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<numba.targets.cpu.CPUContext object at 0x11ee88b70>, <llvmlite.llvmpy.core.Builder object at 0x11deb50f0>, (iter(Jag... [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}, i1}}*', opname 'alloca', operands ()>]>,))
kwargs = {}

    def wrapper(*args, **kwargs):
        kwargs.pop('loc')     # drop unused loc
>       return fn(*args, **kwargs)
E       TypeError: outer() takes 1 positional argument but 4 were given

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/targets/base.py:1157: TypeError

During handling of the above exception, another exception occurred:

self = <tests.test_numba.Test testMethod=test_numba_getiter>

    def test_numba_getiter(self):
        a = JaggedArray.fromiter([[1.1, 2.2, 3.3], [], [4.4, 5.5]])
        a2 = JaggedArray.fromcounts([2, 0, 1], a)
        @numba.njit
        def test1(x):
            out = 0.0
            for xi in x:
                for xij in xi:
                    out += xij
            return out
>       assert test1(a) == 16.5

tests/test_numba.py:373:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/dispatcher.py:370: in _compile_for_args
    raise e
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/dispatcher.py:327: in _compile_for_args
    return self.compile(tuple(argtypes))
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler_lock.py:32: in _acquire_compile_lock
    return func(*args, **kwargs)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/dispatcher.py:659: in compile
    cres = self._compiler.compile(args, return_type)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/dispatcher.py:83: in compile
    pipeline_class=self.pipeline_class)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:940: in compile_extra
    return pipeline.compile_extra(func)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:372: in compile_extra
    return self._compile_bytecode()
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:871: in _compile_bytecode
    return self._compile_core()
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:858: in _compile_core
    res = pm.run(self.status)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler_lock.py:32: in _acquire_compile_lock
    return func(*args, **kwargs)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:254: in run
    raise patched_exception
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:245: in run
    stage()
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:733: in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:683: in _backend
    lowered = lowerfn()
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:670: in backend_nopython_mode
    self.metadata)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/compiler.py:1109: in native_lowering_stage
    lower.lower()
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/lowering.py:177: in lower
    self.lower_normal_function(self.fndesc)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/lowering.py:218: in lower_normal_function
    entry_block_tail = self.lower_function_body()
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/lowering.py:243: in lower_function_body
    self.lower_block(block)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/lowering.py:258: in lower_block
    self.lower_inst(inst)
../miniconda3/envs/awkward/lib/python3.7/contextlib.py:130: in __exit__
    self.gen.throw(type, value, traceback)
../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/errors.py:635: in new_error_context
    six.reraise(type(newerr), newerr, tb)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

tp = <class 'numba.errors.LoweringError'>
value = LoweringError('Failed in nopython mode pipeline (step: nopython mode backend)\nouter() takes 1 positional argument but...ore developers\ndirectly at: https://gitter.im/numba/numba\n\nThanks in advance for your help in improving Numba!\n\n')
tb = None

    def reraise(tp, value, tb=None):
        if value is None:
            value = tp()
        if value.__traceback__ is not tb:
            raise value.with_traceback(tb)
>       raise value
E       numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
E       outer() takes 1 positional argument but 4 were given
E
E       File "tests/test_numba.py", line 369:
E               def test1(x):
E                   <source elided>
E                   out = 0.0
E                   for xi in x:
E                   ^
E
E       [1] During: lowering "$10.2 = iternext(value=$phi10.1)" at /Users/vhaenel/git/numba-integration-testing/awkward/tests/test_numba.py (369)
E       -------------------------------------------------------------------------------
E       This should not have happened, a problem has occurred in Numba's internals.
E
E       Please report the error message and traceback, along with a minimal reproducer
E       at: https://github.com/numba/numba/issues/new
E
E       If more help is needed please feel free to speak to the Numba core developers
E       directly at: https://gitter.im/numba/numba
E
E       Thanks in advance for your help in improving Numba!

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/six.py:659: LoweringError
================================================================ 1 failed, 22 passed in 29.02 seconds =================================================================
::>> The following tests failed: '['awkward']'
```

**Comment by jpivarski** [comment]
@esc In summary, it looks like you got the error and I didn't because you're running Numba master and I'm running the latest release, 0.43.1. Now the stream of consciousness:

It looks like the key issue is here:

```
args = (<numba.targets.cpu.CPUContext object at 0x11ee88b70>, <llvmlite.llvmpy.core.Builder object at 0x11deb50f0>, (iter(Jag... [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}, i1}}*', opname 'alloca', operands ()>]>,))
kwargs = {}

    def wrapper(*args, **kwargs):
        kwargs.pop('loc')     # drop unused loc
>       return fn(*args, **kwargs)
E       TypeError: outer() takes 1 positional argument but 4 were given

../miniconda3/envs/awkward/lib/python3.7/site-packages/numba/targets/base.py:1157: TypeError
```

some interface that used to have 4 arguments but now takes 1. The stack trace doesn't give a clue about what to look for in the awkward-array code because it fails in Numba... after I passed something bad to Numba, presumably. This is exactly the kind of Numba ↔ extended library dependency that tests like this can fix.

One clue is that it fails on the following line of the tests:

```
E       File "tests/test_numba.py", line 369:
E               def test1(x):
E                   <source elided>
E                   out = 0.0
E                   for xi in x:
E                   ^
E
E       [1] During: lowering "$10.2 = iternext(value=$phi10.1)" at /Users/vhaenel/git/numba-integration-testing/awkward/tests/test_numba.py (369)
```

which is when it tries to make an iterator for the JaggedArray `x`. Iterators are handled globally in awkward-array/awkward-numba/awkward/numba/array/base.py. This happened in the lowering, not the typing, so it's one of two functions: `_AwkwardArray_lower_getiter` or `_AwkwardArray_lower_iternext`. Both of these take 4 arguments and get wrapped by `numba.extending.lower_builtin` and (in the latter case) `numba.targets.imputils.iternext_impl`). There are other functions here that take 4 arguments, but they're _called by_ my code, so if it was one of them, the stack trace would have included a line number from my library. So by process of elimination, it's probably one of these two decorators.

I [just checked Numba's master](https://github.com/numba/numba/search?q=iternext_impl&unscoped_q=iternext_impl) and indeed the interface to `numba.targets.imputils.iternext_impl` has changed. It used to be a decorator by itself (for 4-argument functions) but now it's a 1-argument function returning a decorator. That's where the 4-argument vs 1-argument error comes in. In the head version of Numba, I need to say

```python
@numba.targets.imputils.iternext_impl(numba.targets.imputils.RefType.BORROWED)
```

or

```python
@numba.targets.imputils.iternext_impl(numba.targets.imputils.RefType.NEW)
```

instead of

```python
@numba.targets.imputils.iternext_impl
```

(I'm not sure which, but a segfault would tell me! Probably "borrowed," because my iterator implementation changes the index pointer in place, like Numba's arrayobj, which is also "borrowed.")

However, I _can't_ do that in released versions of Numba because `iternext_impl` is a decorator, not a function returning a decorator. In other words, `iternext_impl` was not considered a stable, public-facing API, though I have need of it—exactly the kind of thing we wanted to learn from these tests.

Would the Numba team consider making this decorator backward compatible? Since 0.43.1 is the latest release (from conda), no Numba versions have been released with the new `iternext_impl` interface. If the old behavior was no argument list implies "borrowed," that behavior could be continued. The presence of an argument list would still require "new" vs "borrowed" to be explicit—[an apparent goal](https://github.com/numba/numba/commit/8aa830ae09ffb658548c5eceebd46b040f82f18c). It might be easy to leave out an argument, but it's hard to mistake no argument list with an argument list!

Who should we contact about asking if this can become a public interface with backward compatibility?

**Comment by esc** [comment]
Thanks for the elaborate comment @jpivarski - I appreciate it. @stuartarchibald @seibert @sklam and I will discuss next week in the Numba developers meeting and get back to you!

**Comment by jpivarski** [comment]
I also just joined https://gitter.im/numba/numba-dev so that I can be contacted there. If there's a few weeks before the next production release of Numba, then there's probably enough time to discuss it. I also learned from your tests that I can debug against `numba==0.44.0dev0` (instead of debugging by reading stack traces). I need to be more plugged into the Numba release cycle to know what these are called and when to check, but presumably I'll see that on the Gitter channel.

**Pull request merged**
