### PR TITLE
Add datashader integration tests

### LINKED ISSUE #20: Add `datashader` to integration test matrix
We've seen some minor regressions over the years so it would be great to add this.

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes #20

### CODE REVIEW

**Comment by philippjfr** [comment]
@esc Doesn't look like it's actually running the datashader integration. Anything I did wrong or is it because it's an external PR?

**Comment by esc** [comment]
I think you will still need to make an entry in the circleci config.

**Comment by esc** [comment]
Yeah, looks like it is being picked up now.

**Comment by philippjfr** [comment]
🤦‍♂ ... thanks!

**Comment by esc** [comment]
I think there is a spurious space in the package spec?

**Comment by philippjfr** [comment]
>I think there is a spurious space in the package spec?

Ah, yes, we use reprs to insert the dependencies into the conda command:

``conda install "pytest >=3.9.3"``

is valid, but:

``conda install pytest >=3.9.3``

is not.

**Comment by esc** [comment]
@philippjfr you can also run this locally for debugging, if you need to.

**Comment by philippjfr** [comment]
>@philippjfr you can also run this locally for debugging, if you need to.

Yeah, sorry been lazy and context switching between this and something else. Bad CI etiquette I know!

**Comment by esc** [comment]
Haha, progress before consensus. 🙉

**Comment by philippjfr** [comment]
This time I did run it locally...will make one more attempt.

**Comment by philippjfr** [comment]
Guess it's because locally it's using my other conda env.

**Comment by esc** [comment]
Now that TexasBBQ is being used this PR requires some tweaking. As you can see here:

https://github.com/numba/numba-integration-testing/blob/master/switchboard.py#L27

You will need to inherit from `GitTarget` now for installation and testing you need to return the command string that should be run.

**Comment by esc** [comment]
@philippjfr you want to give this another spin?

**Comment by philippjfr** [comment]
@esc Thanks for the ping. I'll put it on my stack, hopefully I'll get to it tomorrow.

**Comment by esc** [comment]
o.k. awesome, so this works for now and stops only at import errors, I'll merge this now and then rebase #32 ontop.

**Comment by esc** [comment]
and of course 🤞 that datashader was fine with 0.48

**Pull request merged**
