### PR TITLE
Initial extraction of re-usable bits.

### PR DESCRIPTION
**Pull request by esc**
This generalizes the integration-test setup and moves all re-usable bits
to a new module, the `texasbbq`. This PR tracks extraction of that
module, eventual seperation into a package and re-integration of that
package into the integration-testing

### CODE REVIEW

**Comment by esc** [comment]
Current status:

* New repo at: https://github.com/numba/texasbbq
* New PyPi project https://pypi.org/project/texasbbq/

This PR now uses the `texasbbq` project from PyPi.

**Comment by esc** [comment]
pygbm error can be ignored for the time being

**Comment by seibert** [comment]
all looks good!  it is great to see how compact the description is now that the reusable bits have been externalized.

**Comment by esc** [comment]
@seibert thanks for the merge.

**Pull request merged**
